params_local = {
    # from params_global_constant
    'device_ids': [0, 1],
    'run_step1_SplitTrainTest_Terms': 'T',
    'run_step2_Train': 'T',
    'run_step3_Test': 'T',
    'run_step4_pkl2fa': 'T',
    'run_step7.1_EvaluateWithoutAlpha': 'T',
    'run_step8.1_PredictWithoutAlpha': 'F',
    'run_step5_Diamond4CrossSpecies': 'F',
    'run_step6_FindAlpha': 'F',
    'run_step7_EvaluateAlpha': 'F',
    'run_step8_PredictAlpha': 'F',
    'aa_ss': 'ss8',
    'train_data': 'ALL00',
    'test_data': 'ALL00',
    'dir0': 'test_TrainALL00_TestALL00_ss8/',
    'path_base': '/scem/work/songfu/py_proj/prot_algo/DeepSS2GO/',
    'path_pub_data': '/scem/work/songfu/py_proj/prot_algo/DeepSS2GO/pub_data/',
    'go_file': 'data/go.obo',
    'GOMinRepeat': 50,
    'TrainTestRatio': 0.95,
    'TrainValidRatio': 0.9,
    'batch_size': 32,
    'MAXLEN': 1024,
    'FC_depth': 0,
    'learning_rate': 0.0003,
    'epochs': 50,
    'load_pretrained_model': 0,
    'load_pretrained_model_addr': 'data/model_checkpoint.pth',
    'EarlyStopping_patience': 6,
    'PROT_LETTER_aa': ['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V'],
    'PROT_LETTER_ss8': ['C', 'S', 'T', 'H', 'G', 'I', 'E', 'B'],
    'PROT_LETTER_ss3': ['C', 'E', 'H'],

    # split: params_global_dynamic
    'kernels': [48],
    'filters': [16384],
    'onts': 'all',
}
